<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nested PHP and HTML</title>
</head>

<body>

  <h1>Welcome to the Nested PHP Test Page</h1>

  <?php
  // Start of PHP block
  echo "<div>";
  echo "<p>This paragraph is generated by PHP.</p>";
  ?>
  <!-- HTML within PHP -->
  <p>This paragraph is written directly in HTML, inside a PHP block.</p>
  <?php
  // End of PHP block
  echo "</div>";
  ?>

  <p>This is standard HTML outside of PHP.</p>

</body>

</html>